name: Build and release electron app

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: lerte/ngroker
          token: "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"
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          architecture: "x64"
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
